### ISSUE TITLE
Neovim Charter

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim.github.io#104]
migrate charter from Google Doc to markdown

https://docs.google.com/document/d/1Ubpu9xHpKMRi1QqIb8Wa7QRBc4k0j0xvov5GBMxA0qo/edit?usp=sharing

**Comment by fmoralesc** [comment]
https://gist.github.com/fmoralesc/e6ac18c968dd7bd952be

**Comment by justinmk** [comment]
:) I  am not at a computer. We need some place on the website for charter, roadmap, etc...

**Comment by fmoralesc** [comment]
What do you think of this layout?

![captura de pantalla de 2015-07-03 14-20-47](https://cloud.githubusercontent.com/assets/221465/8503015/bc98e132-218e-11e5-891e-f7285c70a4bb.png)

**Comment by justinmk** [comment]
Good, but the think just one link called "about" is enough. It will contain project management-related stuff.

**Comment by fmoralesc** [comment]
Sure. Do you want it to be a static link or should it be a dropdown with links to different pages?

**Comment by fmoralesc** [comment]
A mockup:

![captura de pantalla de 2015-07-04 02-24-56](https://cloud.githubusercontent.com/assets/221465/8506648/0eec187a-21f6-11e5-9e80-0f1b1846e65f.png)

**Comment by fwalch** [comment]
Hmm.. how will the drop-down look on mobile? (do we even have the menu on mobile currently? I remember there was none at some point)

**Comment by fmoralesc** [comment]
The whole menu is hidden when the view is small, it's something else I
noticed.

**Comment by fmoralesc** [comment]
Latest iteration:

![captura de pantalla de 2015-07-04 14-43-21](https://cloud.githubusercontent.com/assets/221465/8508895/2b5e6f98-225b-11e5-8b83-a88fb2d5b3ab.png)
![captura de pantalla de 2015-07-04 14-43-11](https://cloud.githubusercontent.com/assets/221465/8508896/2b823234-225b-11e5-87f5-ca5cc334d345.png)

I used bootstrap because I'm lazy like that.

**Comment by fwalch** [comment]
Looks nice! Can you align the drop-down with the "About" menu (i.e. open the drop-down "to the right", so that the "Charter" text is below "About")?

**Comment by fmoralesc** [comment]
I'm working on that ;)

**Comment by fmoralesc** [comment]
![captura de pantalla de 2015-07-04 15-13-21](https://cloud.githubusercontent.com/assets/221465/8508976/3e8e21d6-225f-11e5-84c7-450ba9a7d54b.png)

Done ;)

**Comment by justinmk** [comment]
Thanks @fmoralesc !

**Comment by fmoralesc** [comment]
Great!

**Comment by justinmk** [comment]
I like all the additional changes too, like the link and menu hover!

**Comment by fmoralesc** [comment]
It should behave a bit better on smaller screens too ;)
