### ISSUE TITLE
Web site unreachable with DNSSEC

### ISSUE THREAD

**Issue by lifepillar** [neovim/neovim.github.io#114]
Is it possible that neovim.io has DNSSEC validation broken? I get a SERVFAIL error whenever I try to access the site using my own DNS server (which uses dnscrypt-proxy). The site is available through my ISP's DNS service.

I haven't experimented much, but that's the only site I have found in more than one year with DNSSEC, which behaves the same as http://www.dnssec-failed.org.

**Comment by justinmk** [comment]
Maybe @jdavis could comment.

**Comment by jdavis** [comment]
neovim.org used to be under my CloudFlare account (I was paying at the time for other domains so it didn't cost anything extra) but I don't have knowledge/control of anything since it switched to .io. @tarruda has all of that, I believe.

**Comment by tarruda** [comment]
I have registered and manageneovim.io through namecheap, but it seems dnssec isn't supported: https://community.namecheap.com/forums/viewtopic.php?f=6&t=8597

**Comment by cweagans** [comment]
@tarruda We should still run the DNS for neovim.io through Cloudflare. It's a pretty simple process to get up and running, but it will take some coordination. Is there a good time to set this up?

**Comment by tarruda** [comment]
@cweagans I will look into this now

**Comment by tarruda** [comment]
I have setup a cloudflare account and transferred neovim.io to it, but it seems the change can take up to 24 hours

**Comment by tarruda** [comment]
It seems the change is now live, @lifepillar if the site is reachable through dnssec can you close the issue?

**Comment by lifepillar** [comment]
Yes, it appears to be served just fine now!
