### ISSUE TITLE
RSS feed not working over HTTP

### ISSUE THREAD

**Issue by JD557** [neovim/neovim.github.io#121]
It seems that the RSS feed at https://neovim.io/news.xml does not work over plain HTTP (i.e. `curl http://neovim.io/news.xml` returns an empty response).

While this should't be a problem by itself, there seems that the server has a very limited set of cipher suites. For example, while I can run `curl https://neovim.io/news.xml` from my mac, it fails from my CentOS 6 machine. It seems to also fail from https://validator.w3.org/feed/check.cgi?url=https://neovim.io/news.xml.

P.S.: I know this issue is not related to the code on this repo, but I'm not completely sure where this issue belong.

**Comment by tarruda** [comment]
We use [cloudflare SSL](https://www.cloudflare.com/ssl) which seems to have limited browser support(perhaps your CentOS curl is outdated?). I have disabled plain http access but can re-enable if it is causing issues for some clients

**Comment by justinmk** [comment]
AFAICT cloudflare is using a newer (more secure) version of TLS, and some old distros ship with curl and/or wget which don't support the TLS version.

More details here: https://github.com/badges/shields/issues/439#issuecomment-139821618
