### ISSUE TITLE
Needs an "Install Now" button or call-to-action on the homepage

### ISSUE THREAD

**Issue by brycefisher** [neovim/neovim.github.io#134]
Every time I setup a new machine, it takes me 10 minutes of clicking around to find the install instructions. It feels like the main goal of the homepage should be get me to view (and run) the install instructions, so there should be a big button or prominent link on the homepage to help accomplish that IMHO.

**Comment by brycefisher** [comment]
FWIW, I'd be happy to open a PR next week which provides a link to wiki.

**Comment by justinmk** [comment]
@brycefisher PR would be welcome.
