### ISSUE TITLE
News

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim.github.io#148]
- cross-pollination: https://github.com/neomutt/neomutt/pull/415
- actualvim: https://github.com/lunixbochs/actualvim/tree/neovim
    - https://gitter.im/neovim/neovim?at=58b721e47ceae5376a5976f0
        > I'd classify it as four pieces:
        > 1) sublime-facing code intercepts keys and handles reading/writing sublime state and listening for sublime events
        > 2) neovim-facing code inputs keys and handles reading/writing vim state
        > 3) glue code in the middle handles efficient synchronization
        > 4) a pile of forked libraries (neovim, msgpack, asyncio, etc) hacked up to work in the sublime environment
        > you could use as a reference design to port to another language/editor as long as you have the ability to intercept all input
    - popupmenu: https://github.com/lunixbochs/actualvim/issues/57#issuecomment-286452725
        - 50 LOC: https://github.com/lunixbochs/actualvim/commit/bd214f980688546926c17ec84418446674f62f27

- student collaboration: https://gitter.im/neovim/neovim?at=58bc63727ceae5376a75480c
    - https://delftswa.gitbooks.io/desosa-2017/content/neovim/chapter.html
- libuv in cmake; support for more platforms: https://github.com/libuv/libuv/issues/1287
- rkt client: https://gitlab.com/HiPhish/neovim.rkt 
    - https://groups.google.com/d/msg/racket-users/b6w0SEmeIII/GeyxEaAXAwAJ

treesitter:

> tree-sitter is a parser framework. Best way to explain how cool it is, is to look at a test suite for one of its parsers. Here's the test suite for its C parser: https://github.com/tree-sitter/tree-sitter-cpp/tree/master/corpus
> Each test is sample code following by an s-expression.
tree-sitter emits and consumes s-expressions to define an AST!
> the grammars are defined in JS: https://github.com/tree-sitter/tree-sitter-cpp/blob/master/grammar.js . That compiles to C. And the C lib is what Nvim uses. And Nvim wraps the treesitter API, so you can augment parsers dynamically.
> And the API is queryable, so the AST can be searched, and this can be used to define mappings, motions, etc.

## 2020

- `vim.regex()` returns a Vim regex object

**Comment by guyzmo** [comment]
(it's still not set in stone, though, we might not end up running unit tests in lua)

**Comment by timeyyy** [comment]
https://github.com/neovim/neovim/pull/6634 - Should we try and put a shorter news letter out to coincide with the version release?

**Comment by justinmk** [comment]
yep
