### ISSUE TITLE
RSS feed not working

### ISSUE THREAD

**Issue by fpvmorais** [neovim/neovim.github.io#149]
Hello,

Your RSS feed is not ok. 

http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fneovim.io%2Fnews.xml

Gives this message:
Server returned [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

Thank you :)

**Comment by justinmk** [comment]
That is a cloudflare decision, nothing we can do about it. http://askubuntu.com/q/649000
