### ISSUE TITLE
Invalid Atom feed

### ISSUE THREAD

**Issue by smlx** [neovim/neovim.github.io#158]
The feed https://neovim.io/news.xml contains entries with duplicate `<id>` elements. These [should be unique](https://stackoverflow.com/questions/150741/how-do-you-generate-a-good-id-in-atom-documents), and in fact my feed reader refuses to load the feed due to the duplicate elements.

Specifically, newsletters 5 and 6 have the same `<id>`.

**Comment by somini** [comment]
Here's a handy validator: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fneovim.io%2Fnews.xml

**Comment by justinmk** [comment]
This is some Jekyll magic. Need someone to send a patch.

**Comment by somini** [comment]
Instead of doing this by hand [here](https://github.com/neovim/neovim.github.io/blob/master/news.xml) you can use the https://github.com/jekyll/jekyll-feed plugin. It will by default use the same URL even.

**Comment by cweagans** [comment]
Jekyll plugins are a no go on Github Pages AFAIK.

**Comment by cweagans** [comment]
Oh, I see. That's one of the default ones they give you: https://help.github.com/articles/configuring-jekyll-plugins/

**Comment by somini** [comment]
It should be a matter of editing the `_config.yml` file to add the `jekyll-feed` plugin and remove the `feed.xml` file from the root directory.
