### ISSUE TITLE
Why Google Analytics and Fonts?

### ISSUE THREAD

**Issue by taminaru** [neovim/neovim.github.io#183]
Would you be willing to remove this Google Analytics and Fonts 'functionality' from this website? There are better alternatives if you must keep tabs on users' activity.

Some reputable alternatives can be seen here: https://switching.software/replace/google-analytics
https://switching.software/replace/google-fonts

**Comment by jamessan** [comment]
Do we know if anyone actually reviews the analytics?  I didn't even realize we had them and would be fine with getting rid of it.

**Comment by teto** [comment]
same

**Comment by cweagans** [comment]
I review them occasionally but it may not be worthwhile to collect the data in the first place.

**Comment by teto** [comment]
I am in favour of removing it if there is no good solution to replace it but now that we have figures, it would be nice to share them on our @gitter before ditching it (in terms of evolution, absolute numbers etc)

**Comment by cweagans** [comment]
I probably won't be able to do much on that front in the immediate future, but i can give you access if you'd like so that you can pull numbers. if you'd like to go that route, let me know which google account i should use.

**Comment by justinmk** [comment]
send a PR?

**Comment by rockerBOO** [comment]
Moving from Google Fonts with #205
