### ISSUE TITLE
Wrong default C code folding for casted structs

### ISSUE THREAD

**Issue by m1027** [neovim/neovim.github.io#191]
I hope it is okay to bother neovim with this:

When folding C code at curly brances "{" and "}", it does not work correctly for this valid C code:

((const struct s){1, 2, 3})

In this case the opening curly brace starts confusing folding as well as brace matches, thus in turn coloring a lot of subsequent braces read.

Note: When leaving out the outer surrounding braces this does not happen.
Also note: AFAIK this has been the case for traditional vim as well.

Thanks for fantastic neovim.

**Comment by jamessan** [comment]
This is the wrong repository (https://github.com/neovim/neovim is the right one) and this is a [known issue](https://github.com/vim/vim/issues/406) with the syntax highlighting.
