### ISSUE TITLE
PROPOSAL: change how the website is build and developed

### ISSUE THREAD

**Issue by lucastrvsn** [neovim/neovim.github.io#207]
Hello guys! I want to contribute with the neovim's website. Reading all the source code I notice we are using too old technologies for frontend development. My proposal was changing the core of the website to enable some nice features, help new developers to come and contribute and improvements on the website.

So, maybe we can change to using some standard tools like: `webpack` (for bundling all the content), `postcss` (for generating our css), `tailwind` (to get some nice css utilities), `handlebars` (or any other template engine - to build all pages).

What do you guys think? Thanks!

**Comment by cweagans** [comment]
-1 from me. The website is maintainable right now by anyone without in depth front-end web development knowledge. Piling on the normal slew of front-end tooling just raises the barrier to entry for anyone that wants to actually contribute to the website, and we really don't gain that much by adding that tooling: it's a 10 page website. We don't _need_ that tooling.

I would suggest that you detail the specific things that you are having trouble with now, how webpack, postcss, tailwind, and handlebars will help, and how/if the benefit to using those tools is greater than the cost. Starting with the solution doesn't seem like the right way to go here.

**Comment by lucastrvsn** [comment]
Hey! I get your point. No problem!

As a front-end developer I feel the source code is too old and we can improve it to make more readable and beginner friendly. Using node.js tooling are much easier and concise method of develop front-end nowadays. Make some changes of how we can built the website is great (at least for my perspective). Maybe the website is 10 pages now, but how about if it grow? I just want to improve how the website is build and maintained.

Making these changes enable a much more concise way to create pages, content and, of course, update it when necessary. There tools I mention was just a suggestion. I feel using webpack to bundle all the content we can have a more described way to create all the pages. Include all the javascript, css and html without the needing to guess what is doing what. Example: where to put a javascript module to connect with github api to get and list all the sponsors from github sponsors? I will put it inside `sponsor-generator` and manipulate some id from the javascript? When this scripts will be executed? I feel this can be improved and help more people to not have this kind of questions and just contribute to improve how the website is build and grow its content.

We can have like:

```
<root>
  assets
    images
  src
    styles
      global.css (global css styling)
      button.css (button classes shared across pages)
      ....
    pages
       home
         styles.css (especific css for this page)
         some-scripts.js (specific js for this page)
         index.html
       ...
```

And using webpack to bundle all of this in a single `css`, `js` and generating all html pages.

But maybe we don't need all of this, but just changing a little can improve readability and maintainability. Thanks for your commend and point of view!

**Comment by teto** [comment]
to paraphrase one of the greatest: `"A nice looking website, that’s one thing Neovim did right."` . I agree with @cweagans and lean to the KISS side (which as non webdev developer may be different than yours). If we use some tooling we have to make sure it will work in the long run. If you are still willing to help, I was thinking we could add a page to add some screenshots (https://github.com/neovim/neovim.github.io/pull/201 but as a page instead of a blog post). As well as a page to link some external media like https://github.com/neovim/neovim/wiki/Videos. These are my ideas so it would need to be approved by the rest of the team.

**Comment by lucastrvsn** [comment]
No problem, thanks for all your opinions!
