### ISSUE TITLE
Site certificate issue

### ISSUE THREAD

**Issue by zmefz** [neovim/neovim.github.io#217]
Looks like something is wrong with the certificate.

<img width="753" alt="image" src="https://user-images.githubusercontent.com/3994011/114695160-f719a000-9d23-11eb-8526-799850e31ecd.png">

**Comment by cweagans** [comment]
ping @tarruda - are we still serving the site through cloudflare per https://github.com/neovim/neovim.github.io/issues/86 ? It looks like the DNS records were updated to point directly at GH pages. Not sure when that change was made, but I'm guessing it was in the last day or so and it broke HTTPS.

**Comment by tarruda** [comment]
> ping @tarruda - are we still serving the site through cloudflare per #86 ? It looks like the DNS records were updated to point directly at GH pages. Not sure when that change was made, but I'm guessing it was in the last day or so and it broke HTTPS.

Hi @cweagans.  A few months I transferred ownership to @justinmk (CC)

**Comment by cweagans** [comment]
ah, okay. great. thanks! @justinmk lmk if i can help here somehow

**Comment by kamalmarhubi** [comment]
From what I can tell, there's a CNAME record being returned for `neovim.io`:
```
$ dig +noall +answer neovim.io
neovim.io.		1503	IN	CNAME	neovim.github.io.
neovim.github.io.	3303	IN	A	185.199.108.153
neovim.github.io.	3303	IN	A	185.199.111.153
neovim.github.io.	3303	IN	A	185.199.110.153
neovim.github.io.	3303	IN	A	185.199.109.153
```

CNAME records are not really supported for an apex domain. Cloudflare does something called [CNAME flattening](https://blog.cloudflare.com/introducing-cname-flattening-rfc-compliant-cnames-at-a-domains-root/), so if someone copied DNS records from Cloudflare it may explain the issue. I'd suggest setting A records for `neovim.io` pointing directly at Github Pages' servers, [as described in the docs](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain):
```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

@cweagans @justinmk 

This is pretty bad so I hope this information helps resolve it!

**Comment by cweagans** [comment]
I do not have access to fix this directly. Happy to do it if @justinmk wants to hand out access though!

**Comment by justinmk** [comment]
I have updated neovim.io DNS to use cloudflare. SSL should hopefully work in 24 hours.

**Comment by cweagans** [comment]
@justinmk Would it be possible for me to regain access to the Cloudflare control panel + domain registration for the Neovim domains? This is critical infrastructure for the project and I'd be glad to provide some backup for you so that the bus factor isn't so low.

**Comment by justinmk** [comment]
> @justinmk Would it be possible for me to regain access to the Cloudflare control panel + domain registration for the Neovim domains? This is critical infrastructure for the project and I'd be glad to provide some backup for you so that the bus factor isn't so low.

I invited @teto as an admin to the cloudflare account.

**Comment by cweagans** [comment]
:+1: that works! Thanks for looking at this!
