### ISSUE TITLE
Remove jQuery and Update Bootstrap

### ISSUE THREAD

**Issue by rockerBOO** [neovim/neovim.github.io#228]
With Bootstrap 5.0, jQuery is no longer required. The feature we used that required it was the dropdowns in the header nav bar. Currently running Bootstrap 5.0 beta so no breaking issues should come up. 

We can now remove jQuery and include the Bootstrap 5 javascript bundle (including popper.js) and slim down things a little. 

See `_layouts/default.html`

https://getbootstrap.com/docs/5.0/migration/
https://getbootstrap.com/docs/5.0/getting-started/javascript/#still-want-to-use-jquery-its-possible
https://getbootstrap.com/docs/5.0/getting-started/introduction/#bundle

**Comment by XVilka** [comment]
I wonder if it makes sense to use some lighter alternatives to Boostrap like one of these:
- [Skeleton](http://getskeleton.com/)
- [Pure](https://purecss.io/)
- [Materialize](https://materializecss.com/)
- others

**Comment by justinmk** [comment]
> lighter alternatives to Boostrap

could be nice, but adds risk if they aren't as well-maintained ("alive") as bootstrap.

**Comment by justinmk** [comment]
Fixed by https://github.com/neovim/neovim.github.io/pull/350
