### ISSUE TITLE
Dead links in LSP help

### ISSUE THREAD

**Issue by euclio** [neovim/neovim.github.io#237]
I was browsing the online [`lsp.txt` help page](https://neovim.io/doc/user/lsp.html) and I noticed that the links to lua functions are broken (see the link to `vim.lsp.omnifunc`, for example).

[The link itself is pointing to "vim.html" which doesn't exist](https://github.com/neovim/doc/blob/gh-pages/user/lsp.html#L134). I tried generating the HTML help locally and the links are correct, so I'm guessing something is broken in the infrastructure that generates and uploads the docs.

**Comment by justinmk** [comment]
known issue with the help generator. I'm working on a rewrite of the help gen...

**Comment by justinmk** [comment]
This is fixed in the new HTML generator, https://github.com/neovim/neovim/pull/11967  you can preview the results at user2/ : 

https://neovim.io/doc/user2/lsp.html

This is not "live" at the main docs path yet (user/), but will be in the next week or 2.
