### ISSUE TITLE
Update roadmap with 0.6 

### ISSUE THREAD

**Issue by rockerBOO** [neovim/neovim.github.io#238]
We pushed tree-sitter to 0.6 for an official release. Also should update for any other features we are pushing to release in 0.6.

[0.6 milestone](https://github.com/neovim/neovim/milestone/11)
[Roadmap](https://neovim.io/roadmap/)

**Comment by teto** [comment]
https://github.com/neovim/neovim.github.io/pull/231

**Comment by clason** [comment]
#243

**Comment by XVilka** [comment]
Please also update the description of Neovim Sponsors page since it still speaks about 0.5 https://github.com/sponsors/neovim

**Comment by teto** [comment]
I've updated the sponsor page a bit.
