### ISSUE TITLE
doxygen layout is broken

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim.github.io#247]
doxygen generated documentation looks broken, likely an accident of the (_much_ appreciated) CSS updates by @rockerBOO  https://github.com/neovim/neovim.github.io/pulls?q=is%3Apr+author%3ArockerBOO

- https://neovim.io/doc/dev/pages.html
    - ![image](https://user-images.githubusercontent.com/1359421/134363641-41c91032-d7da-4404-8245-103f0113e6a7.png)

## Solution

To fix this we likely need to update these files:

1. https://github.com/neovim/doc/blob/main/ci/doxygen.sh
2. https://github.com/neovim/doc/blob/main/templates/report-header.sh.html

**Comment by rockerBOO** [comment]
Looked a little bit and those 2 files seem ok, but their are others in neovim/neovim that might need to be updated.
 
https://github.com/neovim/neovim/blob/master/src/Doxyfile which references [extra.css](https://neovim.io/doc/dev/extra.css) 

And the relevant files are in https://github.com/neovim/neovim/tree/master/contrib/doxygen

I can take a look when I can but others can feel free to update this.
