### ISSUE TITLE
Broken link for documentation on Neovim.io

### ISSUE THREAD

**Issue by applericky** [neovim/neovim.github.io#253]
Hi,

After looking at the main page there appears to be a broken link at the bottom of the front page. 

![image](https://user-images.githubusercontent.com/7573695/147003528-e3fee611-4dd7-4d90-b89f-b7faab821973.jpeg)

When pressing it the link directs to https://neovim.io/doc/ but the link ends back up on a 404 GitHub page. 

Is it supposed to redirect to https://neovim.io/doc/general/?

Let me know if the link I provided is the correct one or which one it is and I can assist in creating a pull request to correct the issue. 

Thanks.

**Comment by teto** [comment]
it's a tough issue. I am a bit swamped right now but I will fix it in january https://github.com/neovim/neovim.github.io/pull/232

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/documentation-link-on-home-page/1800/2
