### ISSUE TITLE
Blocked in India

### ISSUE THREAD

**Issue by captn3m0** [neovim/neovim.github.io#254]
Ref: https://twitter.com/sanchayan_maity/status/1479131300040564737

Probably because the site is using Flexible SSL on CloudFlare? Please enable TLS on GitHub Pages and switch to strict SSL on CloudFlare (or just host directly on GitHub Pages, now that it supports SSL).

Edit: While I am getting HTTPS, the screenshot doesn't, so I am guessing the SSL is set to Basic on CloudFlare end?

**Comment by captn3m0** [comment]
A thread on how this gets blocked in India: https://mobile.twitter.com/captn3m0/status/1468454402956533761

**Comment by captn3m0** [comment]
This can be validated by running a curl in the Digital Ocean BLR1 region:

``
curl -vvv http://neovim.io
* Rebuilt URL to: http://neovim.io/
*   Trying 104.21.46.99...
* TCP_NODELAY set
* Connected to neovim.io (104.21.46.99) port 80 (#0)
> GET / HTTP/1.1
> Host: neovim.io
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Fri, 07 Jan 2022 05:43:15 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< pragma: no-cache
< cache-control: no-cache
< CF-Cache-Status: DYNAMIC
< Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=2hqS1LbFLUham5M5ruSgyvNkr%2FdVqkRddlK0i9j%2B1uVOqg996gOhw9PxTRFFICta1pe2CxOivOu7Sv1gNKR7zk%2F0Pd7MoCNFeXUV1xInSaIeFSDwuxcuCGxuuUY%3D"}],"group":"cf-nel","max_age":604800}
< NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< Server: cloudflare
< CF-RAY: 6c9ade10b8f51d91-BLR
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400
<
* Connection #0 to host neovim.io left intact
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0"/><style>body{margin:0px;padding:0px;}iframe{width:100%;height:100%}</style><iframe src="http://www.airtel.in/dot/" width="100%" height="100%" frameborder=0></iframe>
```

**Comment by captn3m0** [comment]
Wrote a letter to CloudFlare detailing the issue: https://github.com/captn3m0/hello-cloudflare

**Comment by JeffHochberg** [comment]
Switch from using GitHub Pages to Cloudflare Pages. You can connect your CF instance to GitHub Pages or GitHub repositories and Cloudflare Pages will automatically kick off a build each time you commit changes to your repositories.

**Comment by justinmk** [comment]
@captn3m0 is this still an issue?

**Comment by captn3m0** [comment]
Doesn't look like it (I can't replicate it) but its hard to be certain since the blocking was always intermittent
