### ISSUE TITLE
-u flag init change not acknowledged in nvim

### ISSUE THREAD

**Issue by Incblob** [neovim/neovim.github.io#261]
# Problem: 
when using the -u flag to point to a different init.vim file, nvim (I think) loads the correct file, but this is not acknowledged in either `:checkhealth` nor does `:e $MYVIMRC` point to it. 

This makes it difficult to know if it's actually loading a different config, or if changes to the config are loaded. This is especially true if you are loading variations of the config file for testing (Is the init file loaded, is it a plugin problem, or a syntax error?).  

If you don't have a init.vim in the default folder, `:checkhealth` has a "Missing config" error, which makes it even more confusing. 

# Solution:
Have $MYVIMRC and `:checkhealth` register the new init file and have nvim treat it as the default for the session.

**Comment by gpanders** [comment]
This is the issue tracker for the Neovim website. To file an issue against Neovim itself use https://github.com/neovim/neovim

**Comment by Incblob** [comment]
> 

whoops
