### ISSUE TITLE
Documentation file is hard to read

### ISSUE THREAD

**Issue by HaxtonFale** [neovim/neovim.github.io#264]
This is what the docs look for me on Firefox in what seems to be dark mode. The combination of thin strokes used by the font and contrast between background and text colours makes it hard to read. Would it be possible to use a font that is larger or thicker?
![image](https://user-images.githubusercontent.com/1911208/158179416-fbb22713-3e1f-420d-8df5-115db1f945b1.png)

**Comment by jamessan** [comment]
Can you provide concrete suggestions on what you would like to change (e.g., changes to the CSS)? Does increasing the text zoom on the page make it more readable for you?

The text is perfectly readable to me, so I need your help to determine what and how things can be improved.

**Comment by HaxtonFale** [comment]
I would suggest a clearer monospaced font, with thicker strokes, such as Fira Code. That would probably be enough.

**Comment by rockerBOO** [comment]
The font is the default `monospace` font used in your browser, so you could change it to be a font you like.  Adding additional fonts to download adds more to the page as well as prevents people from using a font they like to use. 

Example for me with a font I set as default monospace font on my computer.

![Screenshot 2022-04-15 at 11-16-43 Nvim documentation help](https://user-images.githubusercontent.com/15027/163588432-f2973e8a-978b-4523-a367-26d393111dca.png)
