### ISSUE TITLE
Wrong hyperlink for 0.8 roadmap milestone

### ISSUE THREAD

**Issue by R00dRallec** [neovim/neovim.github.io#287]
On the [Roadmap page](https://neovim.io/roadmap/), the hyperlink for [0.8+](https://github.com/neovim/neovim/milestone/28) links to Github milestone 0.9.

Shouldn't it link to Github milestone 0.8 --> https://github.com/neovim/neovim/milestone/32 ?

**Comment by justinmk** [comment]
Thanks!
