### ISSUE TITLE
[Bug]: styles for hover state for sponsors logo can be improved

### ISSUE THREAD

**Issue by Roshanjossey** [neovim/neovim.github.io#295]
**Problem**

hover effect on Sponsors logo
![neovim-sponsor](https://user-images.githubusercontent.com/8488446/193444531-614784b3-d6f7-43c6-930f-f3b2de92ca5b.gif)

**Reason**

anchor tag has display: inline style as default.

**Solution**

add style `display: block`

![neovim-sponsor-block](https://user-images.githubusercontent.com/8488446/193444786-8980124a-d66c-4016-ae84-e81db419226c.gif)

We could also discuss if this is the right hover effect for images. It works well for text links but for images, we could go another way.

**Comment by justinmk** [comment]
Thanks for figuring out the issue here, it was bugging me :)

I'm also open to thinking about an improved border style or color for normal text links, for both light/dark mode--we need perhaps a different, or additional/complementary border style for special things in the user docs: https://neovim.io/doc/user2

**Comment by Roshanjossey** [comment]
I did some reading around accessibility of links and using image as link content and came across this https://github.com/a11yproject/a11yproject.com/issues/1344. So, I think it's a good idea to change alt text to explicitly state that it's a link.

For styling image links, doing a brightness filter could a good effect.

> additional/complementary border style for special things in the user docs: neovim.io/doc/user2

I didn't understand what special things in that page was. Could you please elaborate?

**Comment by justinmk** [comment]
> > additional/complementary border style for special things in the user docs: neovim.io/doc/user2
> 
> I didn't understand what special things in that page was. Could you please elaborate?

Things like `<code>`, `<pre>` and special highlights for strings like `CTRL-x`, `TODO` and other symbols found in `:help`. See https://github.com/neovim/neovim.github.io/issues/288
