### ISSUE TITLE
docs: add search (Algolia DocSearch)

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim.github.io#310]
- [x] apply for https://docsearch.algolia.com/
- [x] implement the tips at https://docsearch.algolia.com/docs/tips/
    - 🚫  ~~`sitemap.xml` (also apparently helps with SEO)... can be generated by `gen_help_html.lua`~~
        - Not needed: *sitemap.xml ... will make the indexing faster, but will also give you more control over which page you'd like to include or not.*
    - [x] structured documentation ... we read the `<h1>, ..., <h6>` headings of your page to guess the hierarchy.
    - [x] Add anchors to headings
- [x] add search widget to https://neovim.io/doc/user
- [ ] add required css classes : https://docsearch.algolia.com/docs/required-configuration/#use-the-right-classes-as-recordprops
    - `DocSearch-content`
    - _Every textual element (recordProps content) must be wrapped in a `<p>` or `<li>` tag. This content must be atomic and split into small entities._

## Alternatives

if Algolia doesn't work for some reason...

-  https://pagefind.app/

**Comment by shortcuts** [comment]
great idea :) let me know if you need help implementing it!

**Comment by shortcuts** [comment]
Hey @justinmk, I was playing with the browsing the docs today and saw some potential improvements of the crawler config, here's an example of some changes I've made https://crvdgc.csb.app/

If you like it let me know, I could update the config for the nvim crawler :D

**Comment by justinmk** [comment]
@shortcuts absolutely, can you share the config changes here? First thing I noticed is that the search results doesn't have that weird space.

neovim.io (has a weird space):

<img width="233" alt="image" src="https://github.com/neovim/neovim.github.io/assets/1359421/7a6877e1-bacb-4198-bbb9-a5dfd03de053">

your site:

<img width="224" alt="image" src="https://github.com/neovim/neovim.github.io/assets/1359421/cd7afbbe-91c7-4d21-8f86-9e3ecbc8248d">

**Comment by shortcuts** [comment]
> absolutely, can you share the config changes here?

Sure, I only changed the `recordProps` but there could still be improvements made especially if we want to highlight some parts of the docs with [pageRank](https://docsearch.algolia.com/docs/record-extractor/#boost-search-results-with-pagerank)

```js
          recordProps: {
            lvl0: {
              selectors: [
                "header h1",
                "article h1",
                "main h1",
                "h1",
                "head > title",
              ],
              defaultValue: "Documentation",
            },
            lvl1: ["article h2", "main h2", "h2"],
            lvl2: ["article h3", "main h3", "h3"],
            lvl3: ["article h4", "main h4", "h4"],
            lvl4: ["article h5", "main h5", "h5"],
            lvl5: ["article h6", "main h6", "h6"],
            content: [".help-tag", ".help-tag-right"],
          },
```

> First thing I noticed is that the search results doesn't have that weird space.

I guess there might be some theming overlap with your CSS, looking at the code I can see that bootstrap apply some padding over the `mark` element, which might cause these small spaces

**Comment by shortcuts** [comment]
hey @justinmk, I have a bit of time this weekend if you want I can provide a PR to fix the DocSearch style along with updating the config on the Algolia side

**Comment by justinmk** [comment]
@shortcuts yes, style updates are very appreciated whenever you get a chance.

> along with updating the config on the Algolia side

If you have other config hints to share please do, though I guess that can't be done as a PR.

**Comment by justinmk** [comment]
> I'm a DocSearch maintainer and I work on the Crawler at Algolia, I can update the config from there if you don't have time to do it

Interesting... 😆  yes, that would be great! The "diff" of changes would be nice to see here, for reference.

**Comment by shortcuts** [comment]
> The "diff" of changes would be nice to see here, for reference.

Here's a screenshot of the diff from the Crawler UI directly, and the textual one in case you want to manually revert it. I applied the change but did not ran it yet in case you wanted to do it yourself or wait for the next schedule to kick in.

<img width="910" alt="Screenshot 2023-06-27 at 22 16 59" src="https://github.com/neovim/neovim.github.io/assets/20689156/bbb41c60-9c80-47e1-a3a3-561a115d60bc">

```diff
- recordProps: {
-   lvl0: {
-     selectors: "",
-     defaultValue: "Documentation",
-   },
-   lvl1: ["header h1", "article h1", "main h1", "h1", "head > title"],
-   lvl2: ["article h2", "main h2", "h2"],
-   lvl3: ["article h3", "main h3", "h3"],
-   lvl4: ["article h4", "main h4", "h4"],
-   lvl5: ["article h5", "main h5", "h5"],
-   lvl6: ["article h6", "main h6", "h6"],
-   //content: ["div.old-help-para", "div.help-para"],
-   content: [".help-tag", ".help-tag-right"],
- },
+ recordProps: {
+   lvl0: {
+     selectors: [
+       "header h1",
+       "article h1",
+       "main h1",
+       "h1",
+       "head > title",
+     ],
+     defaultValue: "Documentation",
+   },
+   lvl1: ["article h2", "main h2", "h2"],
+   lvl2: ["article h3", "main h3", "h3"],
+   lvl3: ["article h4", "main h4", "h4"],
+   lvl4: ["article h5", "main h5", "h5"],
+   lvl5: ["article h6", "main h6", "h6"],
+   //content: ["div.old-help-para", "div.help-para"],
+   content: [".help-tag", ".help-tag-right"],
+ },
```

----

I'll take a look at the rendering issue :)
