### ISSUE TITLE
css: request to add `overflow-x: auto` to `.old-help-para`

### ISSUE THREAD

**Issue by vagreargnatry** [neovim/neovim.github.io#315]
Hello, could you add `overflow-x: auto` to `.old-help-para`?
This is the picture's doc link: https://neovim.io/doc/user/lsp.html#lsp-buf
Before I add `overflow-x: auto` to `.old-help-para` in chrome console, there has horizontal scroll bar and text overflow.
May be this line (sorry, I'm not sure): https://github.com/neovim/neovim/blob/master/scripts/gen_help_html.lua#L911

before:
![before](https://user-images.githubusercontent.com/104709852/212841168-a22bd073-97d3-4921-bad2-c5b526af4c13.png)
after:
![after](https://user-images.githubusercontent.com/104709852/212841200-c68eaf3f-466b-4480-8ced-cd118b897a0b.png)

**Comment by justinmk** [comment]
pr welcome that implements the idea in https://github.com/neovim/neovim/pull/21644#issuecomment-1372311433

**Comment by vagreargnatry** [comment]
Could you accpet change `white-space: pre` to `white-space: pre-wrap` in `.old-help-para` and add `word-break: break-all` to HTML a tag? After reading https://github.com/neovim/neovim/pull/21644 I think this may have a good effect on my laptop.

![result](https://user-images.githubusercontent.com/104709852/213087067-dee8c6b2-410e-4977-8b66-55b94dcb152e.png)

**Comment by teto** [comment]
for this kind of simple change, better submit a PR as we can test on our own machines and if ok then the improvement is a click away.

**Comment by wookayin** [comment]
Partially fixed by https://github.com/neovim/neovim/pull/28678 and https://github.com/neovim/neovim/pull/28755, although being a different solution (wrap instead of scrollbar).
