### ISSUE TITLE
doc improvement suggestion for `treesitter-query-modeline`

### ISSUE THREAD

**Issue by michaelrommel** [neovim/neovim.github.io#326]
Small issue in the website version of the `treesitter-query-modeline` section: The example should show two versions of modelines separated with a single blank line. On the website this is rendered in one continuous box, it might be more readable, if it would have been split into two separate boxes:

<img width="854" alt="image" src="https://user-images.githubusercontent.com/919935/231849802-9bc67f2b-6d4c-44a9-a6f8-79b67034f61e.png">

**Comment by clason** [comment]
The website is autogenerated from the docs; so this is an issue for neovim/neovim. I'll just fix it there.
