### ISSUE TITLE
Activating virtualenv by default

### ISSUE THREAD

**Issue by karambaq** [neovim/neovim.github.io#327]
I was wondering why `pyright` doesn't know where is my imports at even tho I have venv in the same folder and point in on it. 

And then I tried to activate venv before opening neovim, in this case it works fine. 

I'm wondering how can I make it default behaviour? 
And here someone says that it's actual should be a default behaviour so I'm wondering what's wrong with by installation. 
https://www.reddit.com/r/neovim/comments/ga0s7w/use_python_venv_with_neovim/

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/14233969/236661274-2a80912f-7281-4f31-8462-766fd75f3577.png">

Checkhealth on both sides:

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/14233969/236661418-cb209198-d771-4a9a-b61a-e559cb10f0f2.png">

**Comment by clason** [comment]
This is not an issue about the website. For questions about Neovim, ask on Discourse or Matrix.
