### ISSUE TITLE
change tagline 

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim.github.io#76]
We need a new tagline to replace "rebirth for the 21st century", which was just a placeholder. 

...Also because the current tagline is nearly identical the XEmacs tagline (go to http://www.xemacs.org/ and look at your browser window title). Yep.

I like the tagline

> vim out of the box

 because it conveys several important themes of Neovim:

- Neovim *is* vim (lowercase Vim), *not* a clone or a greenfield rewrite
- The [out-of-the-box][1] experience (for new users as well as stock installations) is very important
- Neovim opens [Pandora's box][2] by exposing an API (the philosophical--if not technical--inverse of the [Emacs][3] [approach][4])
- Neovim attempts to be less prescriptive about use cases (contrary to Vim's `:help design-not`)

[1]: http://en.wikipedia.org/wiki/Out_of_the_box_feature
[2]: http://en.wikipedia.org/wiki/Pandora's_box
[3]: https://lists.gnu.org/archive/html/emacs-devel/2014-09/msg00559.html
[4]: http://lwn.net/Articles/615386/

---

Side note:

Marketing is lame and stuff, but it's important. Spending a sliver of energy to form a competent image is an inexpensive way to gain attention on the "leaf nodes". People have finite time, and they have to make quick judgments about where they spend their attention, and even the most enlightened humans discard 99% of stimuli by quick superficial assessments simply because there is not enough time to deeply investigate everything.

**Comment by Pyrohh** [comment]
Does this need to be open? It looks like #77 dealt with this.

**Comment by justinmk** [comment]
@Pyrohh I still want to change the giant "this is the next generation" copy on the main page. Birth, generation, copulation, progeny, ancestry, etc., is a cliche; we can find better imagery.

**Comment by tarruda** [comment]
Sorry for not seeing this until now(I only started using the "participating" filter from github notifications until a few weeks ago). I have no problems with any of these changes, so feel free to merge it.
