### ISSUE TITLE
Highlight user benefits on website

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim.github.io#88]
From https://vi.stackexchange.com/questions/34/what-is-neovim-how-is-it-different-from-vim-and-why-should-i-care, the website could probably do better in explaining what's so great about Neovim from a user perspective. The existing points are more targeted at (plugin) developers, I think.

Just wanted to write this down somewhere; I think it might be worthwhile to address this before the initial release.

**Comment by fwalch** [comment]
Another related point: while the [list of Neovim-related projects](https://github.com/neovim/neovim/wiki/Related-projects) is useful for developers that want to see what others have tried/are working on, it's probably too confusing for end users. For example, there are multiple projects that are seemingly similar (e.g. OS X GUIs), but in reality many of them might be just experimental/not compatible with latest `master`/...

At the first release, I think the Neovim website should be updated to have a list of GUIs (and possibly other projects) that are compatible with the Neovim release and work well enough for end users. For example, I hope https://github.com/rogual/neovim.app will be such a project for OSX.

**Comment by Pyrohh** [comment]
> At the first release, I think the Neovim website should be updated to have a list of GUIs (and possibly other projects) that are compatible with the Neovim release and work well enough for end users. For example, I hope https://github.com/rogual/neovim.app will be such a project for OSX.

I'm not sure we should be endorsing specific GUIs, but I haven't thought about this much. I like how we have many GUIs mentioned in the wiki, and the fact that the wiki is easily editable by users. However, the main reason I like it is because it's more representative of the Neovim community, as opposed to the website. Maybe we could just point to the wiki, but I'd like to hear your take on this.

**Comment by fwalch** [comment]
> I like how we have many GUIs mentioned in the wiki

Me too, but I'd say that's more from a developer's viewpoint.. someone just looking for a GUI to use will  probably be confused. Three OS X GUIs? Which one should they use? Many of the projects currently linked in the wiki are only experiments.

I'm not dead set about putting this on the website, but it might be the most appealing way.. instead of the current "planned features", we could do a "feature showcase", including GUI projects that emerged as "defaults" for respective platforms. That is, if such a thing happens.. but I don't think there will be many stable, maintained Cocoa GUIs, for example.

Little bit more context: http://www.reddit.com/r/neovim/comments/30akdf/new_osx_gui_project/cps6nyz

**Comment by Pyrohh** [comment]
> I'm not dead set about putting this on the website, but it might be the most appealing way.. instead of the current "planned features", we could do a "feature showcase", including GUI projects that emerged as "defaults" for respective platforms. That is, if such a thing happens.. but I don't think there will be many stable, maintained Cocoa GUIs, for example.

Maybe... I'm skeptical of such a distinction being made on the website between regular community projects and "first class" community projects (i.e. everything that isn't mentioned on the website might be looked at as inferior). IMHO the wiki is the best place for this stuff currently because it's very clear that these are projects using Neovim, but are managed independently of it. I think that if we mention things on the website, we might get bug reports for things which are actually bugs in an external GUI.

**Comment by fwalch** [comment]
> (i.e. everything that isn't mentioned on the website might be looked at as inferior)

That should definitely not happen... maybe just create a second list on the Wiki where only "mature" projects are listed? Then again, how to define "mature"... *sigh* maybe this is a bad idea.

**Comment by Pyrohh** [comment]
> Then again, how to define "mature"

That was my main issue. People are generally terrible at comparing things, e.g."language1 is better and more mature than language2, I thought about it for at least 10 minutes!!".

I think if a project is reasonably popular then it will already be on the wiki and already be in use. junegunn's vim-plug, for example, hasn't had that much written about it, but it seems to have gotten popular via word of mouth (correct me if I'm wrong on this). I think the same can be said about many plugins and software in general.
