### ISSUE TITLE
neovim.org deeplinks broken

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim.github.io#95]
How is the redirection to the new .io domain set up? Is it possible to support deeplinks? Currently, e.g. neovim.org/doc redirects to the front page.

**Comment by tarruda** [comment]
AFAIK it's not possible. Name resolution happens before HTTP and has no knowledge of "paths"

The only way to make this possible would be to setup another HTTP server for neovim.org that redirects to the corresponding path in neovim.io

**Comment by tarruda** [comment]
I'm not sure though, I'm saying this based on my superficial knowledge of the protocols involved.

**Comment by fwalch** [comment]
I'm surely missing something, but neovim.org/doc and neovim.io/doc should point to the same webserver, which should get the requested URL (`/doc`) and deliver the contents.. not sure where the `/doc` is cut off in the .org case.

**Comment by tarruda** [comment]
Ok it was just an error in the configuration. I set it up to redirect to `http://neovim.github.io` when it should be `http://neovim.github.io/`. Reference: https://www.namecheap.com/support/knowledgebase/article.aspx/385/77/how-do-i-set-up-url-forwarding-for-a-domain

**Comment by tarruda** [comment]
This is fixed for me so I will close. If there's still a problem feel free to reopen
